name: CI/CD pipline with Docker


on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a simple test
        run: echo "Pipline is running successfully! no errors found."

      - name: Build Docker image
        run: docker build -t my-app-image:latest .
